name: Build

on: 
  pull_request: # on a pull request to each of these branches
    branches:
      - main

env: 
  NODE_VERSION: 19

jobs: 
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps: 
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run build