name: Lint

on:
  pull_request:
    branches:
      - main
  
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install
        
      # ESLint and Prettier must be in `package.json`
      - name: Run prettier
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
