# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '45 13 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
        stale-issue-message: 'This issues has not been upodated for 60 days, are you planning to work on it?'
        stale-pr-message: 'This pull request has not been updated for 60 days, it might be better to close is and reopen when you have more time to work on it.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
